spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/ss
    username: admin
    password: 123456
ss:
  snowflake:
    worker-id: 1
    datacenter-id: 1
  user-port:
    min: 10000
    max: 20000
  host: hk.hellozjf.com
  boss-thread-num: 2
  worker-thread-num: 2