DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id VARCHAR(32) NOT NULL COMMENT '主键ID',
	create_time DATETIME NOT NULL COMMENT '创建时间',
	update_time DATETIME NOT NULL COMMENT '修改时间',
	is_del CHAR(1) NOT NULL COMMENT '是否删除，Y已删除，N未删除',
	username VARCHAR(30) NOT NULL COMMENT '用户名',
	password VARCHAR(30) NOT NULL COMMENT '密码',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    port INT NULL DEFAULT NULL COMMENT '端口',
	PRIMARY KEY (id)
);